from fpdf import FPDF
from pathlib import Path
from datetime import datetime, UTC
import os

WORKDIR = Path.cwd() / 'runtime'


def generate_pdf(payload):
    session_id = payload.get('session_id')
    filename = WORKDIR / f"RTI_{session_id}.pdf"
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font('Arial', size=12)

    pio = payload.get('pio_address', 'PIO address not verified')
    pdf.multi_cell(0, 8, f"To,\nThe Public Information Officer,\n{pio}\n\n")
    
   
    letter_content = payload.get('rti_letter_english', 'Error: RTI letter content missing.')
    
    pdf.multi_cell(0, 8, letter_content)
    pdf.ln(6)
    pdf.set_font('Arial', size=9)
    pdf.multi_cell(0, 6, f"Generated by RTI Warrior | Session: {session_id} | {datetime.now(UTC).isoformat()}")
    pdf.output(str(filename))
    

    if not filename.exists():
        raise RuntimeError(f"FPDF failed to create file at {filename}")

    return {'pdf_file_path': str(filename), 'pages': pdf.page_no(), 'size_bytes': filename.stat().st_size}